# NumPy Practice Questions

**Instructions:** Dear Students Each question is self‑explanatory. Read the markdown prompt and write the code in the cell below it where marked `# answer here`. Keep solutions simple and focused on the asked concept.

- Q1–Q30: Single-topic questions in sequence (basics → indexing → operations → aggregations → reshaping/broadcasting → utilities).

- Q31–Q35: Multi‑concept (combine 2–3 ideas you practiced).

- Q36–Q40: Use a single dataset loaded via **pandas** and perform **NumPy** operations on it. The file `students_scores.csv` is already available in the same folder as this notebook.


### Q1. Create a 1D NumPy array from the Python list `[1, 2, 3, 4, 5]` and print its type and contents.

In [1]:
import numpy as np

my_list = [1, 2, 3, 4, 5]

my_array = np.array(my_list)

print("type: ",type(my_array))
print("contents: ",my_array)

type:  <class 'numpy.ndarray'>
contents:  [1 2 3 4 5]


### Q2. Create a 2D NumPy array from `[[1, 2, 3], [4, 5, 6]]` and print its `shape` and `ndim`.

In [3]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])

shape = array.shape
ndim = array.ndim

print("shape: ", shape)
print("number of dimension: ",ndim)

shape:  (2, 3)
number of dimension:  2


### Q3. Create an array of 6 zeros and print it.

In [4]:
import numpy as np

zeros_array = np.zeros(6)

print(zeros_array)

[0. 0. 0. 0. 0. 0.]


### Q4. Create an array of 5 ones (float) and print it.

In [5]:
import numpy as np

ones_array = np.ones(5, dtype=float)

print(ones_array)

[1. 1. 1. 1. 1.]


### Q5. Use `np.arange` to create an array from 2 to 14 (inclusive of 2, exclusive of 14) with a step of 2 and print it.

In [6]:
import numpy as np

range_array = np.arange(2, 14, 2)

print(range_array)


[ 2  4  6  8 10 12]


### Q6. Use `np.linspace` to create 5 evenly spaced values from 0 to 1 and print them.

In [7]:
import numpy as np

linespace_array = np.linspace(0, 1, 5)

print(linespace_array)

[0.   0.25 0.5  0.75 1.  ]


### Q7. Create an integer array `[10, 20, 30]` then convert it to `float` dtype and print both arrays.

In [8]:
import numpy as np

int_array = np.array([10, 20, 30])

float_array = int_array.astype(float)

print("integer array: ", int_array)
print("float array: ", float_array)

integer array:  [10 20 30]
float array:  [10. 20. 30.]


### Q8. Create an array of 12 numbers from 0 to 11 and reshape it to `3x4`; print the reshaped array.

In [9]:
import numpy as np

array_12 = np.arange(12)

reshaped_array = array_12.reshape(3, 4)

print(reshaped_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Q9. For the array `a = np.array([[1,2,3],[4,5,6]])`, print `a.shape`, `a.ndim`, and `a.size`.

In [10]:
import numpy as np

a = np.array([[1, 2, 3],[4, 5, 6]])

print("shape: ", a.shape)
print("number of dimension: ", a.ndim)
print("size: ", a.size)

shape:  (2, 3)
number of dimension:  2
size:  6


### Q10. For the array `a = np.array([1,2,3], dtype=np.int32)`, print `a.dtype` and `a.itemsize`.

In [12]:
import numpy as np

a = np.array([1, 2, 3], dtype=np.int32)

print("data type: ", a.dtype)
print("item size: ", a.itemsize)

data type:  int32
item size:  4


### Q11. Given `arr = np.array([10, 20, 30, 40, 50])`, print the first element, last element, and the element at index 2.

In [13]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("first element: ", arr[0])
print("last element: ", arr[-1])
print("element at index 2: ", arr[2])

first element:  10
last element:  50
element at index 2:  30


### Q12. Given `arr = np.array([5, 10, 15, 20, 25])`, use negative indexing to print the last two elements.

In [14]:
import numpy as np


arr = np.array([5, 10, 15, 20, 25])

print(arr[-2:])


[20 25]


### Q13. Given `arr = np.array([0,1,2,3,4,5,6,7,8,9])`, print the slice from index 2 to 7 (exclusive).

In [15]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


print(arr[2:7])


[2 3 4 5 6]


### Q14. Given `m = np.arange(1,13).reshape(3,4)`, print the second row and the third column (as 1D slices).

In [16]:
import numpy as np


m = np.arange(1, 13).reshape(3, 4)


print("Second row:", m[1, :])
print("Third column:", m[:, 2])


Second row: [5 6 7 8]
Third column: [ 3  7 11]


### Q15. Given `m = np.arange(1,13).reshape(3,4)`, print the submatrix containing rows 0 to 1 and columns 1 to 3.

In [17]:
import numpy as np


m = np.arange(1, 13).reshape(3, 4)


print(m[0:2, 1:4])


[[2 3 4]
 [6 7 8]]


### Q16. Given `arr = np.arange(1,11)`, create a boolean mask for even numbers and print the even elements.

In [18]:
import numpy as np

arr = np.arange(1, 11)


even_mask = arr % 2 == 0


print(arr[even_mask])


[ 2  4  6  8 10]


### Q17. Given `arr = np.arange(1,11)`, set all odd elements to `-1` (modify in place) and print the result.

In [19]:
import numpy as np


arr = np.arange(1, 11)


arr[arr % 2 != 0] = -1

print(arr)


[-1  2 -1  4 -1  6 -1  8 -1 10]


### Q18. Given `arr = np.array([1,2,3])`, add `5` to every element and print the result (element‑wise).

In [20]:
import numpy as np

arr = np.array([1, 2, 3])


result = arr + 5


print(result)


[6 7 8]


### Q19. Given `a = np.array([1,2,3])` and `b = np.array([4,5,6])`, print `a + b` and `a * b` (element‑wise).

In [21]:
import numpy as np


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


print("a + b:", a + b)
print("a * b:", a * b)


a + b: [5 7 9]
a * b: [ 4 10 18]


### Q20. Given `a = np.array([1,2,3])` and `b = np.array([[10],[20],[30]])`, use broadcasting to compute `a + b` and print it.

In [22]:
import numpy as np


a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

result = a + b

print(result)


[[11 12 13]
 [21 22 23]
 [31 32 33]]


### Q21. Given `arr = np.array([3, 7, 2, 9, 5])`, print its `sum`, `mean`, `min`, and `max`.

In [23]:
import numpy as np

arr  =  np.array([3, 7, 2, 9, 5])

print("sum: ", arr.sum())
print("mean: ", arr.mean())
print("min: ", arr.min())
print("max: ", arr.max())

sum:  26
mean:  5.2
min:  2
max:  9


### Q22. Given `m = np.arange(1,13).reshape(3,4)`, print the sum along axis 0 and along axis 1.

In [24]:
import numpy as np


m = np.arange(1, 13).reshape(3, 4)


print("Sum along axis 0:", m.sum(axis=0))
print("Sum along axis 1:", m.sum(axis=1))


Sum along axis 0: [15 18 21 24]
Sum along axis 1: [10 26 42]


### Q23. Given `arr = np.array([10, 20, 5, 40, 25])`, print the indices of the `max` and `min` elements using `np.argmax` and `np.argmin`.

In [25]:
import numpy as np

arr = np.array([10, 20, 5, 40, 25])

print("Index of maximum element:", np.argmax(arr))
print("Index of minimum element:", np.argmin(arr))



Index of maximum element: 3
Index of minimum element: 2


### Q24. Given `arr = np.array([3, 3, 1, 2, 2, 2, 5])`, print the sorted array and the unique values using `np.unique`.

In [26]:
import numpy as np


arr = np.array([3, 3, 1, 2, 2, 2, 5])


print("Sorted array:", np.sort(arr))
print("Unique values:", np.unique(arr))


Sorted array: [1 2 2 2 3 3 5]
Unique values: [1 2 3 5]


### Q25. Given `arr = np.array([9, 1, 5, 3, 7])`, sort it in ascending order and print the result (do not modify original).

In [27]:
import numpy as np


arr = np.array([9, 1, 5, 3, 7])

sorted_arr = np.sort(arr)


print(sorted_arr)


[1 3 5 7 9]


### Q26. Given `a = np.array([1,2,3])` and `b = np.array([4,5,6])`, horizontally concatenate them and print the result.

In [28]:
import numpy as np


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


concatenated_result = np.hstack((a, b))

print(concatenated_result)


[1 2 3 4 5 6]


### Q27. Given `A = np.array([[1,2],[3,4]])` and `B = np.array([[5,6],[7,8]])`, stack them vertically and print the result.

In [29]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

stacked_result = np.vstack((A, B))

print(stacked_result)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Q28. Given `arr = np.arange(1,13)`, split it into 3 equal parts and print each part.

In [30]:
import numpy as np


arr = np.arange(1, 13)

split_parts = np.split(arr, 3)

for part in split_parts:
    print(part)


[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


### Q29. Set a random seed (e.g., 42), generate 5 random integers from 0 to 9 using `np.random.randint`, and print them.

In [31]:
import numpy as np


np.random.seed(42)


random_integers = np.random.randint(0, 10, 5)


print(random_integers)


[6 3 7 4 6]


### Q30. Given `arr = np.array([-3, 1, -1, 4, -2, 5])`, use `np.where` to replace negative values with `0` and print the new array.

In [32]:
import numpy as np


arr = np.array([-3, 1, -1, 4, -2, 5])

new_arr = np.where(arr < 0, 0, arr)

print(new_arr)


[0 1 0 4 0 5]


### Q31. Create a 3D array of shape `(2, 3, 4)` using `np.arange` then compute the mean along axis 2 and print the result.

In [33]:
import numpy as np


arr_3d = np.arange(24).reshape(2, 3, 4)


mean_along_axis_2 = arr_3d.mean(axis=2)

print(mean_along_axis_2)


[[ 1.5  5.5  9.5]
 [13.5 17.5 21.5]]


### Q32. Create an array from `[5, 10, 15, 20, 25]`, slice out `[10, 15, 20]`, then normalize that slice to range 0–1 using min‑max formula and print it.

In [34]:
import numpy as np


arr = np.array([5, 10, 15, 20, 25])


slice_arr = arr[1:4]


normalized_slice = (slice_arr - slice_arr.min()) / (slice_arr.max() - slice_arr.min())


print(normalized_slice)


[0.  0.5 1. ]


### Q33. Create two 1D arrays `a=[1,2,3]` and `b=[4,5,6]`; compute the dot product and also form a `3x2` matrix from `a` and `b` and print both results.

In [35]:
import numpy as np


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)


matrix_3x2 = np.column_stack((a, b))

print("Dot product:", dot_product)
print("3x2 Matrix:\n", matrix_3x2)


Dot product: 32
3x2 Matrix:
 [[1 4]
 [2 5]
 [3 6]]


### Q34. Create an array of 12 values (1–12), reshape it to `3x4`, then count how many values are greater than `6` and print the count.

In [36]:
import numpy as np


arr = np.arange(1, 13)


reshaped_arr = arr.reshape(3, 4)


count_greater_than_6 = np.sum(reshaped_arr > 6)


print(count_greater_than_6)


6


### Q35. Create an array from 0–9; replace all odd numbers with `-1` *except* keep the first and last elements unchanged; print the final array.

In [37]:
import numpy as np


arr = np.arange(10)


arr[1:-1][arr[1:-1] % 2 != 0] = -1

print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8  9]


### Dataset for Q36–Q40

A CSV file **`students_scores.csv`** is already placed in this folder (Link-https://drive.google.com/file/d/1B7zDahhmQzXkQmvskS27H07B4Xftf9xA/view?usp=sharing).  

Columns: `id, math, english, science` (10 students). Use **pandas** to import the file and then perform **NumPy** operations.


### Q36. Import `students_scores.csv` as a pandas DataFrame `df`. Then convert the `math`, `english`, and `science` columns to separate NumPy arrays and print their shapes.

In [40]:
from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv("students_scores.csv")
df.head()

Saving students_scores.csv to students_scores (1).csv


,id,math,english,science
0,S01,78,65,72
1,S02,56,70,60
2,S03,88,81,90
3,S04,45,55,48
4,S05,92,76,85


In [41]:
math_array = df['math'].to_numpy()
english_array = df['english'].to_numpy()
science_array = df['science'].to_numpy()

print("shape of math array: ", math_array)
print("shape of english array: ", english_array)
print("shape of  science array: ", science_array)

shape of math array:  [78 56 88 45 92 67 73 59 84 61]
shape of english array:  [65 70 81 55 76 62 80 58 79 69]
shape of  science array:  [72 60 90 48 85 71 66 64 88 57]


### Q37. Using NumPy on the arrays from Q36, compute the mean score of each subject (math, english, science) and print them.

In [42]:
import numpy as np

math_array = df['math'].to_numpy()
english_array = df['english'].to_numpy()
science_array = df['science'].to_numpy()

math_mean = np.mean(math_array)
english_mean = np.mean(english_array)
science_mean = np.mean(science_array)

print("mean score of math: ", math_mean)
print("mean scorte of english: ", english_array)
print("mean score of science: ", science_array)


mean score of math:  70.3
mean scorte of english:  [65 70 81 55 76 62 80 58 79 69]
mean score of science:  [72 60 90 48 85 71 66 64 88 57]


### Q38. Using NumPy, compute each student’s **total score** (math + english + science) and print the `id` of the student with the highest total.

In [43]:
import numpy as np

math_array = df['math'].to_numpy()
english_array = df['english'].to_numpy()
science_array = df['science'].to_numpy()

total_score = math_array + english_array + science_array

max_index = np.argmax(total_score)

student_id_with_highest_score = df['id'].iloc[max_index]

print("student ID with highest total score: ", student_id_with_highest_score)

student ID with highest total score:  S03


### Q39. Using NumPy, standardize the `math` scores to **z-scores**: `(x - mean) / std` and print the first 5 standardized values.

In [44]:
import numpy as np


math_array = df['math'].to_numpy()

math_mean = np.mean(math_array)
math_std = np.std(math_array)


standardized_math = (math_array - math_mean) / math_std


print("First 5 standardized math scores:", standardized_math[:5])


First 5 standardized math scores: [ 0.53032869 -0.98489614  1.21906724 -1.74250855  1.49456267]


In [ ]:
# this is how you can approach question number 39
# dont fear about std(standard deviation , just google it and you understand its simple, else you can connect for doubts)


import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("students_scores.csv")

# Extract math column as NumPy array
math_scores = df["math"].values

# Compute z-scores
z_scores = (math_scores - np.mean(math_scores)) / np.std(math_scores)

# Print first 5 standardized values
print(z_scores[:5])


### Q40. Using NumPy logical operations, count how many students scored **≥ 70 in all three subjects** and print that count.

In [45]:
import numpy as np


math_array = df['math'].to_numpy()
english_array = df['english'].to_numpy()
science_array = df['science'].to_numpy()


students_above_70 = np.logical_and(np.logical_and(math_array >= 70, english_array >= 70), science_array >= 70)


count_students_above_70 = np.sum(students_above_70)


print("Number of students who scored ≥ 70 in all subjects:", count_students_above_70)


Number of students who scored ≥ 70 in all subjects: 3
